[versions]
agp = "8.3.2"
kotlin = "1.9.23"
coreKtx = "1.13.1"
wear = "1.3.0"
wearInput = "1.1.0"
activity = "1.9.0"
coroutines = "1.8.1"
vosk = "0.3.47"
securityCrypto = "1.1.0-alpha06"
googlePlayServicesAuth = "21.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }
wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wearInput" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
vosk-android = { group = "com.alphacephei", name = "vosk-android", version.ref = "vosk" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googlePlayServicesAuth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
